#!/bin/bash

cd /home/SGSCom
./mouseEmu &

while true;
do

r=$( netstat -lnt | grep 80)
echo "test connection"
if [[ -z "$r" ]];
then
echo "sleep 1s"
sleep 1s
else
break
fi
done

echo "service up"
cgexec -g cpu:chromium /home/bitinvo/electron/electron --use-gl=egl --kiosk --touch-devices --touch-events --disable-pinch --overlay-scrollbars --overscroll-history-navigation=0 /home/bitinvo/electron/browser &
sleep 3s
echo $(pidof '/home/bitinvo/electron/electron --type=zygote --no-sandbox') > /tmp/electron.pid